config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :kittens
  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[show edit update destroy]

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    respond_to do |format|
      if @kitten.save
        format.html { redirect_to kitten_url(@kitten), notice: 'Kitten was successfully created.' }
      else
        format.html { render :new, status: unprocessable_entitiy }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @kitten.update(kitten_params)
        format.html { redirect_to kitten_url(@kitten), notice: 'Kitten was successfully updated' }
      else
        format.html { render :edit, status: unprocessable_entitiy }
      end
    end
  end

  def destroy
    @kitten.destroy
    respond_to do |format|
      format.html { redirect_to kittens_url, notice: 'Kitten was successfully destroyed.' }
    end
  end

  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: kitten) do |form| %>
  <% if kitten.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this kitten from being saved:</h2>

      <ul>
        <% kitten.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :cuteness, style: "display: block" %>
    <%= form.number_field :cuteness %>
  </div>

    <div>
    <%= form.label :softness, style: "display: block" %>
    <%= form.number_field :softness %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1> Edit Kitten </h1>

<%= render 'form', kitten: @kitten %> <br>
<%= button_to 'Delete Kitten', @kitten, method: :delete  %> <br><br>
<%= link_to "Show Kitten", @kitten %> <br>
<%= link_to "Index", root_path %>

app/views/kittens/index.html.erb
<p style="color: green"><%= notice %></p>
<h1> All Kittens </h1>

<%= link_to 'new kitten', new_kitten_path %> <br>

<% @kittens.each do |kitten| %>
  <br> Name: <%= kitten.name %> <br>
  Age: <%= kitten.age %> <br>
  Cuteness: <%= kitten.cuteness %> <br>
  Softness: <%= kitten.softness %> <br>
  <%= button_to 'Delete Kitten', @kitten, method: :delete  %> <br>
  <%= link_to 'Show Kitten', kitten  %> <br>
<% end %>

app/views/kittens/new.html.erb
<h1> New Kitten </h1>

<%= render 'form', kitten: @kitten %>

app/views/kittens/show.html.erb
<p style="color: green"><%= notice %></p>

<h1> Show Kitten </h1>

Name: <%= @kitten.name %> <br>
Age: <%= @kitten.age %> <br>
Cuteness: <%= @kitten.cuteness %> <br>
Softness: <%= @kitten.softness %> <br>

<%= link_to 'Edit Kitten', edit_kitten_path %> <br> <br>
<%= button_to 'Delete Kitten', @kitten, method: :delete  %> <br><br>
<%= link_to 'index', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>